
services:
  main_app:
    build:
      context: ./app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://lotta:Jk9!Zt13#Qp@db:5432/postgres

  view_cart:
    build:
      context: ./view_cart
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://lotta:Jk9!Zt13#Qp@db:5432/postgres

  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: Jk9!Zt13#Qp
      POSTGRES_USER: lotta
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    name: multi_container_application_deployment_default
    driver: bridge
volumes:
  postgres_data:
    name: multi_container_application_deployment_postgres_data

