version: '3.8'

services:
  main_app:
    build:
      context: ./main_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://username:password@db/mydatabase"

  view_cart:
    build:
      context: ./view_cart
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://username:password@db/mydatabase"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
